### ISSUE TITLE
error on down 1

### ISSUE THREAD

**Issue by EltonSouza** [gosidekick/migration#4]
panic: runtime error: slice bounds out of range

goroutine 20 [running]:
github.com/gosidekick/migration/v2.downFiles(0x7ffdad30cb7d, 0xf, 0xd, 0xd, 0x0, 0x0, 0xc00007bdc0, 0x513e2a)
        /home/travis/gopath/src/github.com/gosidekick/migration/migration.go:27 +0x1f6
github.com/gosidekick/migration/v2.down(0x7d2b60, 0xc0000aa3c0, 0x7ffdad30cb7d, 0xf, 0x0, 0x0, 0xc0000869c0, 0x7d2b60, 0xc0000aa3c0, 0xc0000869c0, ...)
        /home/travis/gopath/src/github.com/gosidekick/migration/migration.go:48 +0x8f
github.com/gosidekick/migration/v2.doDown(0x7d2b60, 0xc0000aa3c0, 0xc000056080, 0x1, 0x1, 0x7ffdad30cb7d, 0xf, 0xc0000869c0, 0x1, 0x0, ...)
        /home/travis/gopath/src/github.com/gosidekick/migration/migration.go:194 +0xed
github.com/gosidekick/migration/v2.Run(0x7d2b60, 0xc0000aa3c0, 0x7ffdad30cb7d, 0xf, 0x7ffdad30cb38, 0x3f, 0x7ffdad30cb95, 0x4, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/gosidekick/migration/migration.go:160 +0x2c9
github.com/gosidekick/migration/v2/cmd.migrate.func2(0x7ffdad30cb7d, 0xf, 0x7ffdad30cb38, 0x3f, 0x7ffdad30cb95, 0x4, 0xc0000ae2c0, 0xc0000a6300, 0xc0000821e0, 0x7d2b60, ...)
        /home/travis/gopath/src/github.com/gosidekick/migration/cmd/exec.go:58 +0xa6
created by github.com/gosidekick/migration/v2/cmd.migrate
        /home/travis/gopath/src/github.com/gosidekick/migration/cmd/exec.go:57 +0x294

**Comment by felipeweb** [comment]
I can't reproduce travis run ok https://travis-ci.org/gosidekick/migration/builds/543756015

**Comment by crgimenes** [comment]
@EltonSouza , can you send the migration files to test?

**Comment by EltonSouza** [comment]
this error was because I'm passed a wrong path to migration folder, but I think is good have to validation in case someone makes the same mistake.
