### ISSUE TITLE
error on status

### ISSUE THREAD

**Issue by EltonSouza** [gosidekick/migration#5]
panic: runtime error: slice bounds out of range

goroutine 20 [running]:
github.com/gosidekick/migration/v2.Status(0x7d2b60, 0xc0000aa3c0, 0x7fffc4ccfb7d, 0xf, 0xc0000869c0, 0x0, 0xc000168060, 0x1, 0x1, 0x0, ...)                                        
        /home/travis/gopath/src/github.com/gosidekick/migration/migration.go:186 +0x1be
github.com/gosidekick/migration/v2.Run(0x7d2b60, 0xc0000aa3c0, 0x7fffc4ccfb7d, 0xf, 0x7fffc4ccfb38, 0x3f, 0x7fffc4ccfb95, 0x6, 0x0, 0x0, ...)                                      
        /home/travis/gopath/src/github.com/gosidekick/migration/migration.go:162 +0x24d
github.com/gosidekick/migration/v2/cmd.migrate.func2(0x7fffc4ccfb7d, 0xf, 0x7fffc4ccfb38, 0x3f, 0x7fffc4ccfb95, 0x6, 0xc0000ae420, 0xc0000a6300, 0xc0000821e0, 0x7d2b60, ...)      
        /home/travis/gopath/src/github.com/gosidekick/migration/cmd/exec.go:58 +0xa6
created by github.com/gosidekick/migration/v2/cmd.migrate
        /home/travis/gopath/src/github.com/gosidekick/migration/cmd/exec.go:57 +0x294

**Comment by felipeweb** [comment]
I can't reproduce Travis run ok https://travis-ci.org/gosidekick/migration/builds/543756015

**Comment by EltonSouza** [comment]
this error was because I'm passed a wrong path to migration folder, but I think is good have to validation in case someone makes the same mistake.
